- hosts: localhost
  gather_facts: no
  become: no
  tasks:
    - name: stat public key
      stat: path="{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
      register: pub_key_path

    - name: create .ssh directory
      file: path="{{ lookup('env', 'HOME') }}/.ssh mode=0700 state=directory
      when: not pub_key_path.stat.exists

    - name: generate ssh key
      command : ssh-keygen -q -t rsa -f "{{ lookup('env', 'HOME') }}/.ssh/id_rsa -C "" -N ""
      creates: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
      when: not pub_key_path.stat.exists

    - name: update SSH Keys
      delegate_to: localhost
      vault_ssh_sign_key: 
        key_path:  "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
        ssh_mount: ssh-production
        ssh_profile: root 
        signed_key_path: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa-cert.pub"