---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: grab secret from Vault
      vault_fact: path={{ path }} attr={{ secret }} fact=vault_secret
      delegate_to: localhost

    - name: print secret
      debug: msg="{{ vault_secret }}"
      delegate_to: localhost